### ISSUE TITLE
Explain UserRecords better in User Doc.

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-doc#251]
These should be repeated in all client SDK: (starts with JS SDK?)

1. Introduce the concept and different between User and UserRecord
2. Introduce discoverUserByXX() functions, and explain it is a shorthand function for directly querying UserRecords.
3. Introduce Signup functions and fill in UserRecord by default (not yet implemented on development side)

**Comment by bensonby** [comment]
Also to add documentation for helper functions, e.g.

- `get UserRecord`
- `query.havingEmails`
- `query.havingUsernames`

reference: https://github.com/SkygearIO/skygear-SDK-JS/pull/42

**Comment by rickmak** [comment]
With https://github.com/SkygearIO/skygear-server/issues/54. I propose to take away the need of interacting with `_user`(`UserAuth`) as much as we can. My suggestion is to make `signupWithEmail(email, pw, {wholeUserAttrs...}`.

By this API change, the user will aware they create `User` (Record) object with attributes. Since in application logic, we interact with `User` (Record), not `UserAuth`. So instead of adding `Records` everywhere. I propose to explicitly call `UserAuth` (_user) when needed. Through out the doc, `User` will always mean user record.

So the `discoverUserByXX` func, will not suffix with `Recod`.

**Comment by chpapa** [comment]
@rickmak Without giving in much thought, it sounds great to me.

The only loop hole I can think of is, is there any different between the *currentUser* user, or User records fetch from other functions?

From Skygear docs it seems there are no different for now. But I would expect for *currentUser* there will be something special (such as when is the last login, when is the session created)

Another possibility is we just make user User meant UserRecord, we also make functions handle changing of UserRecord attribute correctly (So maybe a default ACL is you can change your own Profile but not others)

And for other special information about currentUser, we put it in another global object. (Such as session)

Thoughts?

**Comment by rickmak** [comment]
In contrast to introduce another global object. I will propose to make the `currentUser` is a `UserRecord` with meta keys, like `_accessToken`, `_session_since`, etc. Those will will got ignored on save, just for read.
