### ISSUE TITLE
[Questions] admin ui / REST api / index

### ISSUE THREAD

**Issue by txchen** [SkygearIO/skygear-doc#404]
Hi, I just found this project, very promising. I was looking into open source parse-server, but still found it has some issues then I started looking around again and found this one.

Basically I have 3 questions currently:

* Do you have plan to create docs for REST API, like parse? Suppose my backend server wants to use skygear, I need to use REST IMO.
* Will you open source your dashboard/admin UI? I haven't setup the skygear-server yet, I think the UI is not a part of it, I may be wrong.
* How do you manage index of the records? Can I query based on any field?

Thanks a lot! :)

**Comment by chpapa** [comment]
Hi @txchen, glad you found it interesting!

1. Yes we plan to have it but we can't commit to a roadmap yet. (And you are welcomed to help! :) 

2. We will open source the CMS (business user dashboard) in Q1 2017. If you need it now we can share the link and a simple README to you but no extensive doc yet.

For the dashboard of for developer (I.e. The UI you saw at portal.skygear.io) there are no plan to open source it yet but on open source implementation you can always config in another way. In fact most features at developer dashboard are just changing of environment variable.

3. You can query on any field, and have 100% control to the postgreSQL server even if you use our hosted solutions to create index :)

Hope it helps! Since it is the issue tracker of docs, I am closing this issue but you are always welcome to send us any question via Google group https://groups.google.com/forum/#!forum/skygear-user-group
