### ISSUE TITLE
Cleanup the legacy files at docs.skygear.io

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#431]
For example, the https://docs.skygear.io/release-cycle/ is still at old style and publicly accessible.

**Comment by bensonby** [comment]
Can we restrict access in the s3 folders so that when running s3 sync cli with `--delete` option it cannot delete the existing android API references?

https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/

http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by rickmak** [comment]
Of coz we can, but what is your plan on it? I am not sure travis can run `s3 sync`.

**Comment by bensonby** [comment]
To install awscli using `pip`: http://stackoverflow.com/questions/30808227/how-can-i-clear-s3-bucket-before-travis-deploy

**Comment by rickmak** [comment]
Alright, please let me know the policy and setup with you.

PS: I will prefer white list what to delete. But not relay on the setting to block the delete. But it is fine.
