### ISSUE TITLE
Missing not found state and UI feedback on pasting and enter

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-doc#515]
Step to reproduce

1. paste `discoverUserByEmails` into search box
1. press enter
1. nothing happen

Expected result

- Let me know no result found

Side track:

If you type `discoverUserByEmails`, the UX is actually okay. Since there will be some result before it become empty. :cry:

**Comment by tensiuyan** [comment]
I think include code block in the search may solve this problem. Also add a no result please try other keywords page. Will handle this issue in #516

**Comment by rickmak** [comment]
>  include code block

Why is it related?

> no result please try other keywords page

Page? I am referring the search dropdown.

**Comment by chpapa** [comment]
@tensiuyan I think it is not related. We should have a "Not found" design for #516

**Comment by tensiuyan** [comment]
@rickmak 
Sorry -

1. Currently we haven't indexed the code blocks. That's why when you search "discoverUserByEmails", you got no result. I think as a user, I will expect a result when I search an APIs. See if you agree?

2. Yup I am talking about the search dropdown. When there's no result, we should display "No result found. Please try other keywords". 

Sorry was typing too fast.
